# Generated by Django 5.0.6 on 2024-06-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('classifier_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=100)),
                ('description', models.TextField(blank=True, db_collation='Cyrillic_General_CI_AS', null=True)),
            ],
            options={
                'db_table': 'Classifier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Complexsolution',
            fields=[
                ('solution_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=100)),
                ('description', models.TextField(blank=True, db_collation='Cyrillic_General_CI_AS', null=True)),
            ],
            options={
                'db_table': 'ComplexSolution',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Complexsolutionproducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ComplexSolutionProducts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customerrequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=100)),
                ('request_date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'CustomerRequest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customerrequestitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_solution', models.IntegerField()),
                ('quantity_product', models.IntegerField()),
            ],
            options={
                'db_table': 'CustomerRequestItems',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=100)),
                ('role', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=50)),
            ],
            options={
                'db_table': 'Employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=100)),
                ('description', models.TextField(blank=True, db_collation='Cyrillic_General_CI_AS', null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Soldproduct',
            fields=[
                ('sold_id', models.AutoField(primary_key=True, serialize=False)),
                ('sale_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'SoldProduct',
                'managed': False,
            },
        ),
    ]
